server:
  port: 8070

spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT&useSSL=false
        username: root
        password: 123456

mybatis:
  typeAliasesPackage: com.example.demo.domin
  mapperLocations: classpath:mappers/*.xml

logging:
  level: 
    cn.tedu.ssm.mapper: debug